[package]
name = "api-utils"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
