name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:

  main-ci:
    runs-on: ubuntu-latest
    steps:

      - uses: eqtylab-actions/install-nix-action@v31

      - uses: eqtylab-actions/checkout@v3

      - run: nix develop -L -c true

      - run: nix develop -c ets -sc just ci
